spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:mysql://localhost:3306/blog
    user: root
    password: root
logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  token:
    secret: secret
    expired: 3600000